name: Terraform Release

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: 'AWS Access Key ID (ASIAXXFSYSEESDFFABDT)'
        required: true
        type: string
      aws_secret_access_key:
        description: 'AWS Secret Access Key (mx3nIkt+VvQngB9PYTifmNkGk2N6rgX104mPjpFK)'
        required: true
        type: string
      aws_session_token:
        description: 'AWS Session Token (IQoJb3JpZ2luX2VjEGcaCXVzLXdlc3QtMiJGMEQCIC9K36MVPA/eGdJptY8f9+pb3bSWbT9QHYolola9TlMMAiBej/yzx+uiT+m1TrAJyLCMV3LAtdTT6vME5SVz9M85/yqqAggvEAIaDDUzMDgwMzM2NDEwNSIMxLBJP3SpVCuONpJGKocCQSwR9B/X1GEC9xrOcNZ1tdHgAuEsxU1u27k6Wfz6MhkvtZ4oy/eteKbtJ2Ui+JSvhvDG6bT6C4+OnaF1ocVX6MyJ2id/Ug0/ZQGGfS9pmYSAQMpDWzyoGpYZ6WTggMAYIFnh2SdQQaJbjEOWO40J6UavorLkXw1r57OTDx4CR5NAFBf64dGQJUhvy57wFiH3TbV7aZ8Mdoe9Fqv/c3f3FduypGF2cfBFKj38yk+RmBU79jsU4Fag0Ysv4+zKKcIf0OIXIGtzRm/I5cIvcE+Dd8AKVi1NUTxzLxocgsEzd1OtRcnW0pFAVgSgkKNvKzxpLVT3NN/FpdqQmNB1VEOOJTHHQkMEFSUwh+6rzgY6ngHlbaT2xklk1OPVZ40Yb7L8MgYG3LXBAlGR9nyrVnEUG/2qz6K1Dt6YN/zCWX0OkDwBa0E5UR7ntphZ5tVJy199eFFJjHjAkuALSiSyFEw0NpZNLy+eS8WuUpUfWkEDsakBy6ugJ1uw8oxyY0vB03gbRY5ohQfD6YucLNt72BF1wKHUEYbnea9btMm7xgjGo86CFbkIO4BgNQMzKZamig==)'
        required: true
        type: string
      aws_region:
        description: 'AWS Region'
        required: false
        default: 'us-east-1'
        type: string

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: iac

    env:
      AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      AWS_SESSION_TOKEN: ${{ inputs.aws_session_token }}
      AWS_DEFAULT_REGION: ${{ inputs.aws_region }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply --auto-approve